### ISSUE TITLE
codeBlockPlugin() 调用插件报错

### ISSUE THREAD

**Issue by NockingNocking** [yanyu-fe/vuepress-plugins#1]
import { defineUserConfig, defaultTheme } from 'vuepress'

import codeBlockPlugin from '@yanyu-fe/vuepress-plugin-code-block'

export default defineUserConfig({
  title: '测试',
  // plugins: [['@yanyu-fe/vuepress-plugin-code-block', {}]],
  plugins: [codeBlockPlugin({})]
})

****
**info Initializing VuePress and preparing data...
error error in hook extendsBundlerOptions from vuepress-plugin-code-block
TypeError: Cannot read properties of undefined (reading 'plugins')**
    at Object.extendsBundlerOptions [as hook] (D:\GithubProject\nocking\node_modules\.pnpm\@yanyu-fe+vuepress-plugin-code-block@0.1.0\node_modules\@yanyu-fe\vuepress-plugin-code-block\lib\node\codeBlock.js:83:41)
    at Object.process (D:\GithubProject\nocking\node_modules\.pnpm\@vuepress+core@2.0.0-beta.43\node_modules\@vuepress\core\lib\pluginApi\createHookQueue.js:26:48)
    at dev (D:\GithubProject\nocking\node_modules\.pnpm\@vuepress+bundler-vite@2.0.0-beta.43\node_modules\@vuepress\bundler-vite\lib\dev.js:9:53)
    at Object.dev (D:\GithubProject\nocking\node_modules\.pnpm\@vuepress+bundler-vite@2.0.0-beta.43\node_modules\@vuepress\bundler-vite\lib\viteBundler.js:8:33)
    at Object.app.dev (D:\GithubProject\nocking\node_modules\.pnpm\@vuepress+core@2.0.0-beta.43\node_modules\@vuepress\core\lib\app\createDevApp.js:10:41)
    at dev (D:\GithubProject\nocking\node_modules\.pnpm\@vuepress+cli@2.0.0-beta.43\node_modules\@vuepress\cli\lib\commands\dev\createDev.js:53:33)
D:\GithubProject\nocking\site:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  site@1.0.0 dev: `vuepress dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by aibayanyu20** [comment]
请提供一下插件的版本号

**Comment by NockingNocking** [comment]
> 请提供一下插件的版本号

 "@yanyu-fe/vuepress-plugin-code-block": "^0.1.0"

**Comment by aibayanyu20** [comment]
```ts
import { defineUserConfig } from "vuepress";
import { codeBlockPlugin } from "@yanyu-fe/vuepress-plugin-code-block";
export default defineUserConfig({
  title: "文档",
  plugins: [codeBlockPlugin()],
});
```
更新一下最新的版本试试，要求vuepress的版本大于等于2.0.0-beta.43
