### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'plugins')

### ISSUE THREAD

**Issue by anchuanyuan** [yanyu-fe/vuepress-plugins#2]
error error in hook extendsBundlerOptions from vuepress-plugin-code-block
TypeError: Cannot read properties of undefined (reading 'plugins')
    at Object.extendsBundlerOptions [as hook] (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@yanyu-fe+vuepress-plugin-code-block@0.1.1\node_modules\@yanyu-fe\vuepress-plugin-code-block\lib\node\codeBlock.js:83:41)
    at Object.process (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@vuepress+core@2.0.0-beta.45\node_modules\@vuepress\core\lib\pluginApi\createHookQueue.js:26:48)
    at dev (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@vuepress+bundler-vite@2.0.0-beta.45\node_modules\@vuepress\bundler-vite\lib\dev.js:9:53)
    at Object.dev (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@vuepress+bundler-vite@2.0.0-beta.45\node_modules\@vuepress\bundler-vite\lib\viteBundler.js:8:33)
    at Object.app.dev (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@vuepress+core@2.0.0-beta.45\node_modules\@vuepress\core\lib\app\createDevApp.js:10:41)
    at dev (D:\01-study\vuepress_docs\lib-ui\node_modules\.pnpm\@vuepress+cli@2.0.0-beta.45\node_modules\@vuepress\cli\lib\commands\dev\createDev.js:53:33)
D:\01-study\vuepress_docs\lib-ui\site:

父工程 package.json
{
  "name": "lib-ui",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "site": "pnpm -filter=site  dev",
    "site:build": "pnpm --filter=site  build"
  },
  "packageManger": "pnpm@7.0.1",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@mistjs/eslint-config-vue": "^0.0.2",
    "eslint": "^8.15.0",
    "typescript": "^4.6.4"
  }
}
site  package.json
{
  "name": "site",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "vuepress dev",
    "build": "vuepress build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@vuepress/client": "2.0.0-beta.45",
    "@yanyu-fe/vuepress-plugin-code-block": "^0.1.1",
    "vue": "^3.2.34",
    "vuepress": "2.0.0-beta.45"
  }
}

**Comment by anchuanyuan** [comment]
![image](https://user-images.githubusercontent.com/36631774/169377885-1dabbec2-4393-4543-8dfe-31f4b0db4008.png)

**Comment by aibayanyu20** [comment]
提供一个demo看看
