### ISSUE TITLE
引入插件报错

### ISSUE THREAD

**Issue by loqinyahuive** [yanyu-fe/vuepress-plugins#3]
hi, 你好，最近在学习搭建组件库 ，在使用插件的时候报错，不清楚是否是版本的原因 求教

--错误
> vuepress dev

node:internal/modules/cjs/loader:900
  const err = new Error(message);
              ^

Error: Cannot find module 'node:path'

--config.ts

import { codeBlockPlugin } from "@yanyu-fe/vuepress-plugin-code-block"

export default defineUserConfig({
  lang: 'zh-CN',
  title: 'UI组件库',
  description: '这是我的第一个 VuePress 站点',
  plugins: [codeBlockPlugin()],
  locales: {
    "/": {
      lang: "zh-CN",
      title: "ui-design",
    }
  },
  theme: defaultTheme({
    locales: {
        "/": {
            // navbar: navbar.zh,
            // sidebar: sidebar.zh
        }
    }
}),
})

--site package.json依赖
"devDependencies": {
    "@vuepress/client": "2.0.0-beta.51",
    "@yanyu-fe/vuepress-plugin-code-block": "^0.1.3",
    "vite": "^3.1.7",
    "less": "^4.1.2"
  },
  "dependencies": {
    "vue": "^3.2.40",
    "vuepress": "^2.0.0-beta.51"
  },

**Comment by aibayanyu20** [comment]
在`package.json`中固定如下的版本号：

```json
{
  "devDependencies": {
    "vuepress": "2.0.0-beta.49",
    "@vuepress/plugin-search": "2.0.0-beta.49",
    "@vuepress/theme-default": "2.0.0-beta.49",
    "@yanyu-fe/vuepress-plugin-code-block": "^0.1.3"
  },
  "pnpm": {
    "overrides": {
      "@vuepress/utils": "2.0.0-beta.49",
      "@vuepress/client": "2.0.0-beta.49",
      "@vuepress/plugin-search": "2.0.0-beta.49",
      "@vuepress/shared": "2.0.0-beta.49",
      "@vuepress/theme-default": "2.0.0-beta.49",
      "@vuepress/bundler-vite": "2.0.0-beta.49",
      "@vuepress/cli": "2.0.0-beta.49",
      "@vuepress/prismjs": "2.0.0-beta.49",
      "vuepress": "2.0.0-beta.49"
    }
  }
}
```
由于`vuepress`的breaking change，比较快，导致插件的版本不一致，会导致一些问题，所以固定版本号，避免出现问题。后期会逐步升级。

**Comment by loqinyahuive** [comment]
ok&nbsp; 稍后我试下&nbsp; 赞&nbsp;


。。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yanyu-fe/vuepress-plugins] 引入插件报错 (Issue #3)





 
Closed #3 as completed via 8f68084.

**Comment by aibayanyu20** [comment]
升级到0.2.0

**Comment by loqinyahuive** [comment]
嗯嗯， 可以成功启动啦，能请教下引入组件的问题不？
我组件库用的是.vue 文件， 这个是vite版本不兼容的问题吗
config.ts配置：
import vue from '@vitejs/plugin-vue'

bundler:viteBundler({
    viteOptions:{
        plugins:[vue()],
        resolve:{
            alias:{
                // "ui-design/style":resolve(__dirname,"../../packages/ui/src/style.ts"),
                "ui-repo":resolve(__dirname,"../../packages/components/title/index.js"),
            }
        },
        // css:{
        //     preprocessorOptions:{
        //         less:{
        //          modifyVars:{
        //              "html-dark-selector": "~'html.dark'"
        //          }
        //         }
        //     }
        // }
    },
})
错误信息：
Illegal tag name. Use '&lt;' to print '<'.
下午5:09:04 [vite] Internal server error: Illegal tag name. Use '&lt;' to print '<'.
  Plugin: vite:vue
  File: /Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vuepress+theme-default@2.0.0-beta.51/node_modules/@vuepress/theme-default/lib/client/layouts/Layout.vue
  36 |  const onTouchEnd = (e): void => {
  37 |    const dx = e.changedTouches[0].clientX - touchStart.x
  38 |    const dy = e.changedTouches[0].clientY - touchStart.y
     |                                    ^
  39 |    if (Math.abs(dx) > Math.abs(dy) && Math.abs(dx) > 40) {
  40 |      if (dx > 0 && touchStart.x <= 80) {
      at createCompilerError (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-core@3.2.40/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
      at emitError (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-core@3.2.40/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1602:29)
      at parseChildren (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-core@3.2.40/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:953:21)
      at Object.baseParse (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-core@3.2.40/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:852:23)
      at Object.parse (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-dom@3.2.40/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3119:25)
      at Object.parse (/Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vue+compiler-sfc@3.2.40/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5061:26)
      at createDescriptor (file:///Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.7+vue@3.2.40/node_modules/@vitejs/plugin-vue/dist/index.mjs:62:43)
      at transformMain (file:///Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.7+vue@3.2.40/node_modules/@vitejs/plugin-vue/dist/index.mjs:2158:34)
      at TransformContext.transform (file:///Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.7+vue@3.2.40/node_modules/@vitejs/plugin-vue/dist/index.mjs:2646:16)
      at Object.transform (file:///Users/yahuiqin/workspace/UI/qyh-ui-design/node_modules/.pnpm/vite@3.0.9_less@4.1.3/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:53)
下午5:09:04 [vite] Internal server error: Illegal tag name. Use '&lt;' to print '<'.

**Comment by loqinyahuive** [comment]
> 升级到0.2.0
能帮忙看下这个问题吗？ 是内部解析只解析jsx文件吗？
git地址： git@github.com:loqinyahuive/qyh-ui-design.git
![image](https://user-images.githubusercontent.com/14011669/195573178-24d3783c-4f6d-45cb-94c2-77355375c2a1.png)

**Comment by aibayanyu20** [comment]
不需要导入vue，vuepress默认自带vue插件

**Comment by aibayanyu20** [comment]
配置不对，多看看视频学习一下


<img width="535" alt="image" src="https://user-images.githubusercontent.com/45655660/195588460-25b5401d-2602-4fc5-a631-b4082ad6a608.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/45655660/195588580-41fabb80-10fd-4dc7-86c3-27d6a4f44be8.png">

**Comment by loqinyahuive** [comment]
感谢
